// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * The image factory extensions versions data source provides a list of available extensions for a specific talos version from the image factory.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as talos from "@pulumi/talos";
 *
 * const this = talos.imageFactory.getExtensionsVersions({
 *     talosVersion: "v1.7.5",
 *     filters: {
 *         names: [
 *             "amdgpu",
 *             "tailscale",
 *         ],
 *     },
 * });
 * ```
 */
export function getExtensionsVersions(args: GetExtensionsVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetExtensionsVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:imageFactory/getExtensionsVersions:getExtensionsVersions", {
        "filters": args.filters,
        "talosVersion": args.talosVersion,
    }, opts);
}

/**
 * A collection of arguments for invoking getExtensionsVersions.
 */
export interface GetExtensionsVersionsArgs {
    /**
     * The filter to apply to the extensions list.
     */
    filters?: inputs.imageFactory.GetExtensionsVersionsFilters;
    /**
     * The talos version to get extensions for.
     */
    talosVersion: string;
}

/**
 * A collection of values returned by getExtensionsVersions.
 */
export interface GetExtensionsVersionsResult {
    /**
     * The list of available extensions for the specified talos version.
     */
    readonly extensionsInfos: outputs.imageFactory.GetExtensionsVersionsExtensionsInfo[];
    /**
     * The filter to apply to the extensions list.
     */
    readonly filters?: outputs.imageFactory.GetExtensionsVersionsFilters;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * The talos version to get extensions for.
     */
    readonly talosVersion: string;
}
/**
 * The image factory extensions versions data source provides a list of available extensions for a specific talos version from the image factory.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as talos from "@pulumi/talos";
 *
 * const this = talos.imageFactory.getExtensionsVersions({
 *     talosVersion: "v1.7.5",
 *     filters: {
 *         names: [
 *             "amdgpu",
 *             "tailscale",
 *         ],
 *     },
 * });
 * ```
 */
export function getExtensionsVersionsOutput(args: GetExtensionsVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetExtensionsVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:imageFactory/getExtensionsVersions:getExtensionsVersions", {
        "filters": args.filters,
        "talosVersion": args.talosVersion,
    }, opts);
}

/**
 * A collection of arguments for invoking getExtensionsVersions.
 */
export interface GetExtensionsVersionsOutputArgs {
    /**
     * The filter to apply to the extensions list.
     */
    filters?: pulumi.Input<inputs.imageFactory.GetExtensionsVersionsFiltersArgs>;
    /**
     * The talos version to get extensions for.
     */
    talosVersion: pulumi.Input<string>;
}
