// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * The image factory versions data source provides a list of available talos versions from the image factory.
 */
export function getVersions(args?: GetVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetVersionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:imageFactory/getVersions:getVersions", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getVersions.
 */
export interface GetVersionsArgs {
    /**
     * The filter to apply to the overlays list.
     */
    filters?: inputs.imageFactory.GetVersionsFilters;
}

/**
 * A collection of values returned by getVersions.
 */
export interface GetVersionsResult {
    /**
     * The filter to apply to the overlays list.
     */
    readonly filters?: outputs.imageFactory.GetVersionsFilters;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * The list of available talos versions.
     */
    readonly talosVersions: string[];
}
/**
 * The image factory versions data source provides a list of available talos versions from the image factory.
 */
export function getVersionsOutput(args?: GetVersionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVersionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:imageFactory/getVersions:getVersions", {
        "filters": args.filters,
    }, opts);
}

/**
 * A collection of arguments for invoking getVersions.
 */
export interface GetVersionsOutputArgs {
    /**
     * The filter to apply to the overlays list.
     */
    filters?: pulumi.Input<inputs.imageFactory.GetVersionsFiltersArgs>;
}
