template: external-bridged-provider
provider: talos
organization: pulumiverse
major-version: 0
providerDefaultBranch: main
upstreamProviderOrg: siderolabs
publishRegistry: false
plugins:
    - name: terraform
      version: "1.0.19"
      kind: converter
      # - name: random
      #   version: "4.16.7"
      # - name: aws
      #   version: "6.56.1"
      # - name: local
      #   version: "0.1.5"
      # - name: "null"
      #   version: "0.0.8"
languages:
    - dotnet
    - go
    - nodejs
    - python
publish:
    sdk: "all,!java"
    cdn: false
license:
    ignore:
        # The following is Apache 2.0 licensed but the license file is not detected correctly
        - github.com/cyberphone/json-canonicalization/go/src/webpki.org/jsoncanonicalizer
pulumiConvert: 1
