---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: setup-ci
  pull: always
  image: autonomy/build-container:latest
  commands:
  - sleep 5
  - git fetch --tags
  - install-ci-key
  - docker buildx create --driver docker-container --platform linux/amd64 --name local --use unix:///var/outer-run/docker.sock
  - docker buildx inspect --bootstrap
  environment:
    SSH_KEY:
      from_secret: ssh_key
  volumes:
  - name: outer-docker-socket
    path: /var/outer-run
  - name: docker-socket
    path: /var/run
  - name: buildx
    path: /root/.docker/buildx
  - name: ssh
    path: /root/.ssh

- name: build
  pull: always
  image: golang:1.18
  commands:
  - make install-prereqs
  - make build

- name: release-notes
  pull: always
  image: autonomy/build-container:latest
  commands:
  - make release-notes
  volumes:
  - name: outer-docker-socket
    path: /var/outer-run
  - name: docker-socket
    path: /var/run
  - name: buildx
    path: /root/.docker/buildx
  - name: ssh
    path: /root/.ssh
  when:
    event:
    - tag
  depends_on:
  - build

- name: release
  pull: always
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    - sha512
    draft: true
    files:
    - "_out/pulumi-resource-talos"
    note: _out/RELEASE_NOTES.md
  when:
    event:
    - tag
  depends_on:
  - release-notes

services:
- name: docker
  image: docker:20.10-dind
  entrypoint:
  - dockerd
  commands:
  - --dns=8.8.8.8
  - --dns=8.8.4.4
  - --mtu=1500
  - --log-level=error
  privileged: true
  volumes:
  - name: outer-docker-socket
    path: /var/outer-run
  - name: docker-socket
    path: /var/run
  - name: buildx
    path: /root/.docker/buildx
  - name: ssh
    path: /root/.ssh

volumes:
- name: outer-docker-socket
  host:
    path: /var/ci-docker
- name: docker-socket
  temp:
    medium: memory
- name: buildx
  temp:
    medium: memory
- name: ssh
  temp:
    medium: memory

---
kind: pipeline
type: kubernetes
name: notify

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: slack
  image: plugins/slack
  settings:
    channel: proj-talos-maintainers
    link_names: true
    template: "{{#if build.pull }}\n*{{#success build.status}}✓ Success{{else}}✕ Fail{{/success}}*: {{ repo.owner }}/{{ repo.name }} - <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>\n{{else}}\n*{{#success build.status}}✓ Success{{else}}✕ Fail{{/success}}: {{ repo.owner }}/{{ repo.name }} - Build #{{ build.number }}* (type: `{{ build.event }}`)\n{{/if}}\nCommit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>\nBranch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>\nAuthor: {{ build.author }}\n<{{ build.link }}|Visit build page>"
    webhook:
      from_secret: slack_webhook
  when:
    status:
    - success
    - failure

trigger:
  status:
  - success
  - failure

depends_on:
- default
