// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.Machine.Inputs
{

    /// <summary>
    /// A complete Machine Secrets Certificates configuration
    /// </summary>
    public sealed class CertificatesArgs : global::Pulumi.InvokeArgs
    {
        [Input("etcd", required: true)]
        public Inputs.CertificateArgs Etcd { get; set; } = null!;

        [Input("k8s", required: true)]
        public Inputs.CertificateArgs K8s { get; set; } = null!;

        [Input("k8s_aggregator", required: true)]
        public Inputs.CertificateArgs K8s_aggregator { get; set; } = null!;

        [Input("k8s_serviceaccount", required: true)]
        public Inputs.KeyArgs K8s_serviceaccount { get; set; } = null!;

        [Input("os", required: true)]
        public Inputs.CertificateArgs Os { get; set; } = null!;

        public CertificatesArgs()
        {
        }
        public static new CertificatesArgs Empty => new CertificatesArgs();
    }
}
