// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.Machine.Inputs
{

    public sealed class ConfigurationMachineSecretsCertsArgs : global::Pulumi.InvokeArgs
    {
        [Input("etcd", required: true)]
        public Inputs.ConfigurationMachineSecretsCertsEtcdArgs Etcd { get; set; } = null!;

        [Input("k8s", required: true)]
        public Inputs.ConfigurationMachineSecretsCertsK8sArgs K8s { get; set; } = null!;

        [Input("k8sAggregator", required: true)]
        public Inputs.ConfigurationMachineSecretsCertsK8sAggregatorArgs K8sAggregator { get; set; } = null!;

        [Input("k8sServiceaccount", required: true)]
        public Inputs.ConfigurationMachineSecretsCertsK8sServiceaccountArgs K8sServiceaccount { get; set; } = null!;

        [Input("os", required: true)]
        public Inputs.ConfigurationMachineSecretsCertsOsArgs Os { get; set; } = null!;

        public ConfigurationMachineSecretsCertsArgs()
        {
        }
        public static new ConfigurationMachineSecretsCertsArgs Empty => new ConfigurationMachineSecretsCertsArgs();
    }
}
