// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.Machine.Inputs
{

    public sealed class DisksFiltersInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Filter disks by bus path
        /// </summary>
        [Input("busPath")]
        public Input<string>? BusPath { get; set; }

        /// <summary>
        /// Filter disks by modalias
        /// </summary>
        [Input("modalias")]
        public Input<string>? Modalias { get; set; }

        /// <summary>
        /// Filter disks by model
        /// </summary>
        [Input("model")]
        public Input<string>? Model { get; set; }

        /// <summary>
        /// Filter disks by name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Filter disks by serial number
        /// </summary>
        [Input("serial")]
        public Input<string>? Serial { get; set; }

        /// <summary>
        /// Filter disks by size
        /// </summary>
        [Input("size")]
        public Input<string>? Size { get; set; }

        /// <summary>
        /// Filter disks by type
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Filter disks by uuid
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        /// <summary>
        /// Filter disks by wwid
        /// </summary>
        [Input("wwid")]
        public Input<string>? Wwid { get; set; }

        public DisksFiltersInputArgs()
        {
        }
        public static new DisksFiltersInputArgs Empty => new DisksFiltersInputArgs();
    }
}
