// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.Machine.Inputs
{

    public sealed class GetConfigurationMachineSecretsCertsInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The certificate and key pair
        /// </summary>
        [Input("etcd", required: true)]
        public Input<Inputs.GetConfigurationMachineSecretsCertsEtcdInputArgs> Etcd { get; set; } = null!;

        /// <summary>
        /// The certificate and key pair
        /// </summary>
        [Input("k8s", required: true)]
        public Input<Inputs.GetConfigurationMachineSecretsCertsK8sInputArgs> K8s { get; set; } = null!;

        /// <summary>
        /// The certificate and key pair
        /// </summary>
        [Input("k8sAggregator", required: true)]
        public Input<Inputs.GetConfigurationMachineSecretsCertsK8sAggregatorInputArgs> K8sAggregator { get; set; } = null!;

        [Input("k8sServiceaccount", required: true)]
        public Input<Inputs.GetConfigurationMachineSecretsCertsK8sServiceaccountInputArgs> K8sServiceaccount { get; set; } = null!;

        /// <summary>
        /// The certificate and key pair
        /// </summary>
        [Input("os", required: true)]
        public Input<Inputs.GetConfigurationMachineSecretsCertsOsInputArgs> Os { get; set; } = null!;

        public GetConfigurationMachineSecretsCertsInputArgs()
        {
        }
        public static new GetConfigurationMachineSecretsCertsInputArgs Empty => new GetConfigurationMachineSecretsCertsInputArgs();
    }
}
