// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.Machine.Inputs
{

    /// <summary>
    /// A complete Machine Secrets configuration
    /// </summary>
    public sealed class MachineSecretsInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("certs", required: true)]
        public Input<Inputs.CertificatesInputArgs> Certs { get; set; } = null!;

        [Input("cluster", required: true)]
        public Input<Inputs.ClusterInputArgs> Cluster { get; set; } = null!;

        [Input("secrets", required: true)]
        public Input<Inputs.KubernetesSecretsInputArgs> Secrets { get; set; } = null!;

        [Input("trustdinfo", required: true)]
        public Input<Inputs.TrustdInfoInputArgs> Trustdinfo { get; set; } = null!;

        public MachineSecretsInputArgs()
        {
        }
        public static new MachineSecretsInputArgs Empty => new MachineSecretsInputArgs();
    }
}
