// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Talos
{
    /// <summary>
    /// Talos secrets resource
    /// </summary>
    [TalosResourceType("talos:index:clusterSecrets")]
    public partial class ClusterSecrets : Pulumi.CustomResource
    {
        [Output("configVersion")]
        public Output<Outputs.TalosMachineConfigVersionOutput> ConfigVersion { get; private set; } = null!;

        /// <summary>
        /// Talos Secrets Bundle
        /// </summary>
        [Output("secrets")]
        public Output<Outputs.SecretsBundle> Secrets { get; private set; } = null!;

        /// <summary>
        /// Talos version the config generated for
        /// </summary>
        [Output("talosVersion")]
        public Output<Outputs.TalosVersionOutput> TalosVersion { get; private set; } = null!;


        /// <summary>
        /// Create a ClusterSecrets resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ClusterSecrets(string name, ClusterSecretsArgs? args = null, CustomResourceOptions? options = null)
            : base("talos:index:clusterSecrets", name, args ?? new ClusterSecretsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ClusterSecrets(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("talos:index:clusterSecrets", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "secrets",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ClusterSecrets resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ClusterSecrets Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ClusterSecrets(name, id, options);
        }
    }

    public sealed class ClusterSecretsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// the desired machine config version to generate (default "v1alpha1")
        /// </summary>
        [Input("configVersion")]
        public InputUnion<string, Pulumi.Talos.TalosMachineConfigVersion>? ConfigVersion { get; set; }

        /// <summary>
        /// the desired Talos version to generate config for (backwards compatibility, e.g. v0.8)
        /// </summary>
        [Input("talosVersion")]
        public Input<string>? TalosVersion { get; set; }

        public ClusterSecretsArgs()
        {
            ConfigVersion = "v1alpha1";
        }
    }
}
