// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos
{
    public static class GetImageFactoryOverlaysVersions
    {
        /// <summary>
        /// The image factory overlays versions data source provides a list of available overlays for a specific talos version from the image factory.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Talos = Pulumi.Talos;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @this = Talos.GetImageFactoryOverlaysVersions.Invoke(new()
        ///     {
        ///         TalosVersion = "v1.7.5",
        ///         Filters = new Talos.Inputs.GetImageFactoryOverlaysVersionsFiltersInputArgs
        ///         {
        ///             Name = "rock4cplus",
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetImageFactoryOverlaysVersionsResult> InvokeAsync(GetImageFactoryOverlaysVersionsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetImageFactoryOverlaysVersionsResult>("talos:index/getImageFactoryOverlaysVersions:getImageFactoryOverlaysVersions", args ?? new GetImageFactoryOverlaysVersionsArgs(), options.WithDefaults());

        /// <summary>
        /// The image factory overlays versions data source provides a list of available overlays for a specific talos version from the image factory.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Talos = Pulumi.Talos;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var @this = Talos.GetImageFactoryOverlaysVersions.Invoke(new()
        ///     {
        ///         TalosVersion = "v1.7.5",
        ///         Filters = new Talos.Inputs.GetImageFactoryOverlaysVersionsFiltersInputArgs
        ///         {
        ///             Name = "rock4cplus",
        ///         },
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetImageFactoryOverlaysVersionsResult> Invoke(GetImageFactoryOverlaysVersionsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetImageFactoryOverlaysVersionsResult>("talos:index/getImageFactoryOverlaysVersions:getImageFactoryOverlaysVersions", args ?? new GetImageFactoryOverlaysVersionsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetImageFactoryOverlaysVersionsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The filter to apply to the overlays list.
        /// </summary>
        [Input("filters")]
        public Inputs.GetImageFactoryOverlaysVersionsFiltersArgs? Filters { get; set; }

        /// <summary>
        /// The talos version to get overlays for.
        /// </summary>
        [Input("talosVersion", required: true)]
        public string TalosVersion { get; set; } = null!;

        public GetImageFactoryOverlaysVersionsArgs()
        {
        }
        public static new GetImageFactoryOverlaysVersionsArgs Empty => new GetImageFactoryOverlaysVersionsArgs();
    }

    public sealed class GetImageFactoryOverlaysVersionsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The filter to apply to the overlays list.
        /// </summary>
        [Input("filters")]
        public Input<Inputs.GetImageFactoryOverlaysVersionsFiltersInputArgs>? Filters { get; set; }

        /// <summary>
        /// The talos version to get overlays for.
        /// </summary>
        [Input("talosVersion", required: true)]
        public Input<string> TalosVersion { get; set; } = null!;

        public GetImageFactoryOverlaysVersionsInvokeArgs()
        {
        }
        public static new GetImageFactoryOverlaysVersionsInvokeArgs Empty => new GetImageFactoryOverlaysVersionsInvokeArgs();
    }


    [OutputType]
    public sealed class GetImageFactoryOverlaysVersionsResult
    {
        /// <summary>
        /// The filter to apply to the overlays list.
        /// </summary>
        public readonly Outputs.GetImageFactoryOverlaysVersionsFiltersResult? Filters;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The list of available extensions for the specified talos version.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetImageFactoryOverlaysVersionsOverlaysInfoResult> OverlaysInfos;
        /// <summary>
        /// The talos version to get overlays for.
        /// </summary>
        public readonly string TalosVersion;

        [OutputConstructor]
        private GetImageFactoryOverlaysVersionsResult(
            Outputs.GetImageFactoryOverlaysVersionsFiltersResult? filters,

            string id,

            ImmutableArray<Outputs.GetImageFactoryOverlaysVersionsOverlaysInfoResult> overlaysInfos,

            string talosVersion)
        {
            Filters = filters;
            Id = id;
            OverlaysInfos = overlaysInfos;
            TalosVersion = talosVersion;
        }
    }
}
