// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.Cluster.Inputs
{

    public sealed class KubeconfigKubernetesClientConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The kubernetes CA certificate
        /// </summary>
        [Input("caCertificate")]
        public Input<string>? CaCertificate { get; set; }

        /// <summary>
        /// The kubernetes client certificate
        /// </summary>
        [Input("clientCertificate")]
        public Input<string>? ClientCertificate { get; set; }

        [Input("clientKey")]
        private Input<string>? _clientKey;

        /// <summary>
        /// The kubernetes client key
        /// </summary>
        public Input<string>? ClientKey
        {
            get => _clientKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The kubernetes host
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        public KubeconfigKubernetesClientConfigurationArgs()
        {
        }
        public static new KubeconfigKubernetesClientConfigurationArgs Empty => new KubeconfigKubernetesClientConfigurationArgs();
    }
}
