// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Retrieves the kubeconfig for a Talos cluster
 */
export function getKubeconfig(args: GetKubeconfigArgs, opts?: pulumi.InvokeOptions): Promise<GetKubeconfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:cluster/getKubeconfig:getKubeconfig", {
        "clientConfiguration": args.clientConfiguration,
        "endpoint": args.endpoint,
        "node": args.node,
        "timeouts": args.timeouts,
        "wait": args.wait,
    }, opts);
}

/**
 * A collection of arguments for invoking getKubeconfig.
 */
export interface GetKubeconfigArgs {
    /**
     * The client configuration data
     */
    clientConfiguration: inputs.cluster.GetKubeconfigClientConfiguration;
    /**
     * endpoint to use for the talosclient. If not set, the node value will be used
     */
    endpoint?: string;
    /**
     * controlplane node to retrieve the kubeconfig from
     */
    node: string;
    timeouts?: inputs.cluster.GetKubeconfigTimeouts;
    /**
     * Wait for the kubernetes api to be available
     *
     * @deprecated This attribute is deprecated and no-op. Will be removed in a future version. Use talos.cluster.getHealth instead.
     */
    wait?: boolean;
}

/**
 * A collection of values returned by getKubeconfig.
 */
export interface GetKubeconfigResult {
    /**
     * The client configuration data
     */
    readonly clientConfiguration: outputs.cluster.GetKubeconfigClientConfiguration;
    /**
     * endpoint to use for the talosclient. If not set, the node value will be used
     */
    readonly endpoint: string;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * The raw kubeconfig
     */
    readonly kubeconfigRaw: string;
    /**
     * The kubernetes client configuration
     */
    readonly kubernetesClientConfiguration: outputs.cluster.GetKubeconfigKubernetesClientConfiguration;
    /**
     * controlplane node to retrieve the kubeconfig from
     */
    readonly node: string;
    readonly timeouts?: outputs.cluster.GetKubeconfigTimeouts;
    /**
     * Wait for the kubernetes api to be available
     *
     * @deprecated This attribute is deprecated and no-op. Will be removed in a future version. Use talos.cluster.getHealth instead.
     */
    readonly wait?: boolean;
}
/**
 * Retrieves the kubeconfig for a Talos cluster
 */
export function getKubeconfigOutput(args: GetKubeconfigOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubeconfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:cluster/getKubeconfig:getKubeconfig", {
        "clientConfiguration": args.clientConfiguration,
        "endpoint": args.endpoint,
        "node": args.node,
        "timeouts": args.timeouts,
        "wait": args.wait,
    }, opts);
}

/**
 * A collection of arguments for invoking getKubeconfig.
 */
export interface GetKubeconfigOutputArgs {
    /**
     * The client configuration data
     */
    clientConfiguration: pulumi.Input<inputs.cluster.GetKubeconfigClientConfigurationArgs>;
    /**
     * endpoint to use for the talosclient. If not set, the node value will be used
     */
    endpoint?: pulumi.Input<string>;
    /**
     * controlplane node to retrieve the kubeconfig from
     */
    node: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.cluster.GetKubeconfigTimeoutsArgs>;
    /**
     * Wait for the kubernetes api to be available
     *
     * @deprecated This attribute is deprecated and no-op. Will be removed in a future version. Use talos.cluster.getHealth instead.
     */
    wait?: pulumi.Input<boolean>;
}
