// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.Machine.Outputs
{

    [OutputType]
    public sealed class GetConfigurationMachineSecretsResult
    {
        /// <summary>
        /// The certs for the talos kubernetes cluster
        /// </summary>
        public readonly Outputs.GetConfigurationMachineSecretsCertsResult Certs;
        /// <summary>
        /// The cluster secrets
        /// </summary>
        public readonly Outputs.GetConfigurationMachineSecretsClusterResult Cluster;
        /// <summary>
        /// The secrets for the talos kubernetes cluster
        /// </summary>
        public readonly Outputs.GetConfigurationMachineSecretsSecretsResult Secrets;
        /// <summary>
        /// The trustd info for the talos kubernetes cluster
        /// </summary>
        public readonly Outputs.GetConfigurationMachineSecretsTrustdinfoResult Trustdinfo;

        [OutputConstructor]
        private GetConfigurationMachineSecretsResult(
            Outputs.GetConfigurationMachineSecretsCertsResult certs,

            Outputs.GetConfigurationMachineSecretsClusterResult cluster,

            Outputs.GetConfigurationMachineSecretsSecretsResult secrets,

            Outputs.GetConfigurationMachineSecretsTrustdinfoResult trustdinfo)
        {
            Certs = certs;
            Cluster = cluster;
            Secrets = secrets;
            Trustdinfo = trustdinfo;
        }
    }
}
