// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.Machine.Outputs
{

    /// <summary>
    /// A Machine Secrets Bootstrap data
    /// </summary>
    [OutputType]
    public sealed class KubernetesSecretsResult
    {
        /// <summary>
        /// The aescbc encryption secret for the talos kubernetes cluster
        /// </summary>
        public readonly string? Aescbc_encryption_secret;
        /// <summary>
        /// The bootstrap token for the talos kubernetes cluster
        /// </summary>
        public readonly string Bootstrap_token;
        /// <summary>
        /// The secretbox encryption secret for the talos kubernetes cluster
        /// </summary>
        public readonly string Secretbox_encryption_secret;

        [OutputConstructor]
        private KubernetesSecretsResult(
            string? aescbc_encryption_secret,

            string bootstrap_token,

            string secretbox_encryption_secret)
        {
            Aescbc_encryption_secret = aescbc_encryption_secret;
            Bootstrap_token = bootstrap_token;
            Secretbox_encryption_secret = secretbox_encryption_secret;
        }
    }
}
