// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.Machine.Outputs
{

    [OutputType]
    public sealed class SecretsMachineSecretsCertsK8sServiceaccount
    {
        /// <summary>
        /// key data
        /// </summary>
        public readonly string? Key;

        [OutputConstructor]
        private SecretsMachineSecretsCertsK8sServiceaccount(string? key)
        {
            Key = key;
        }
    }
}
