// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/pulumiverse/pulumi-talos/sdk/go/talos/internal"
)

var _ = internal.GetEnvOrDefault

// The URL of Image Factory to generate schematics. If not set defaults to https://factory.talos.dev.
func GetImageFactoryUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "talos:imageFactoryUrl")
}
