// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace SideroLabs.Pulumi.Talos.Cluster
{
    /// <summary>
    /// Retrieve Kubeconfig for a Talos cluster
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using Pulumi;
    /// using Talos = SideroLabs.Pulumi.Talos;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var machineSecrets = new Talos.Machine.Secrets("machineSecrets");
    /// 
    ///     var talosconfig = new Talos.Client.Configuration("talosconfig", new()
    ///     {
    ///         ClusterName = "example-cluster",
    ///         MachineSecrets = machineSecrets.MachineSecrets,
    ///         Endpoints = new[]
    ///         {
    ///             "10.5.0.2",
    ///         },
    ///     });
    /// 
    ///     var kubeconfig = new Talos.Cluster.Kubeconfig("kubeconfig", new()
    ///     {
    ///         TalosConfig = talosconfig.TalosConfig,
    ///         Endpoint = "10.5.0.2",
    ///         Node = "10.5.0.2",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [TalosResourceType("talos:cluster/kubeconfig:Kubeconfig")]
    public partial class Kubeconfig : global::Pulumi.CustomResource
    {
        /// <summary>
        /// machine endpoint
        /// </summary>
        [Output("endpoint")]
        public Output<string> Endpoint { get; private set; } = null!;

        /// <summary>
        /// The retrieved Kubeconfig
        /// </summary>
        [Output("kubeConfig")]
        public Output<string> KubeConfig { get; private set; } = null!;

        /// <summary>
        /// node to use
        /// </summary>
        [Output("node")]
        public Output<string> Node { get; private set; } = null!;

        /// <summary>
        /// talos client configuration for authentication
        /// </summary>
        [Output("talosConfig")]
        public Output<string> TalosConfig { get; private set; } = null!;


        /// <summary>
        /// Create a Kubeconfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Kubeconfig(string name, KubeconfigArgs args, CustomResourceOptions? options = null)
            : base("talos:cluster/kubeconfig:Kubeconfig", name, args ?? new KubeconfigArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Kubeconfig(string name, Input<string> id, KubeconfigState? state = null, CustomResourceOptions? options = null)
            : base("talos:cluster/kubeconfig:Kubeconfig", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/siderolabs/pulumi-provider-talos",
                AdditionalSecretOutputs =
                {
                    "kubeConfig",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Kubeconfig resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Kubeconfig Get(string name, Input<string> id, KubeconfigState? state = null, CustomResourceOptions? options = null)
        {
            return new Kubeconfig(name, id, state, options);
        }
    }

    public sealed class KubeconfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// machine endpoint
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        /// <summary>
        /// node to use
        /// </summary>
        [Input("node", required: true)]
        public Input<string> Node { get; set; } = null!;

        /// <summary>
        /// talos client configuration for authentication
        /// </summary>
        [Input("talosConfig", required: true)]
        public Input<string> TalosConfig { get; set; } = null!;

        public KubeconfigArgs()
        {
        }
        public static new KubeconfigArgs Empty => new KubeconfigArgs();
    }

    public sealed class KubeconfigState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// machine endpoint
        /// </summary>
        [Input("endpoint")]
        public Input<string>? Endpoint { get; set; }

        [Input("kubeConfig")]
        private Input<string>? _kubeConfig;

        /// <summary>
        /// The retrieved Kubeconfig
        /// </summary>
        public Input<string>? KubeConfig
        {
            get => _kubeConfig;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _kubeConfig = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// node to use
        /// </summary>
        [Input("node")]
        public Input<string>? Node { get; set; }

        /// <summary>
        /// talos client configuration for authentication
        /// </summary>
        [Input("talosConfig")]
        public Input<string>? TalosConfig { get; set; }

        public KubeconfigState()
        {
        }
        public static new KubeconfigState Empty => new KubeconfigState();
    }
}
