// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package talos

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Retrieves the kubeconfig for a Talos cluster
func TalosClusterKubeconfig(ctx *pulumi.Context, args *TalosClusterKubeconfigArgs, opts ...pulumi.InvokeOption) (*TalosClusterKubeconfigResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv TalosClusterKubeconfigResult
	err := ctx.Invoke("talos:index/talosClusterKubeconfig:TalosClusterKubeconfig", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking TalosClusterKubeconfig.
type TalosClusterKubeconfigArgs struct {
	// The client configuration data
	ClientConfiguration TalosClusterKubeconfigClientConfiguration `pulumi:"clientConfiguration"`
	// endpoint to use for the talosclient. if not set, the node value will be used
	Endpoint *string `pulumi:"endpoint"`
	// controlplane node to retrieve the kubeconfig from
	Node     string                 `pulumi:"node"`
	Timeouts map[string]interface{} `pulumi:"timeouts"`
	// Wait for the kubernetes api to be available
	Wait *bool `pulumi:"wait"`
}

// A collection of values returned by TalosClusterKubeconfig.
type TalosClusterKubeconfigResult struct {
	// The client configuration data
	ClientConfiguration TalosClusterKubeconfigClientConfiguration `pulumi:"clientConfiguration"`
	// endpoint to use for the talosclient. if not set, the node value will be used
	Endpoint string `pulumi:"endpoint"`
	// The ID of this resource.
	Id string `pulumi:"id"`
	// The raw kubeconfig
	KubeconfigRaw string `pulumi:"kubeconfigRaw"`
	// The kubernetes client configuration
	KubernetesClientConfiguration TalosClusterKubeconfigKubernetesClientConfiguration `pulumi:"kubernetesClientConfiguration"`
	// controlplane node to retrieve the kubeconfig from
	Node     string                 `pulumi:"node"`
	Timeouts map[string]interface{} `pulumi:"timeouts"`
	// Wait for the kubernetes api to be available
	Wait *bool `pulumi:"wait"`
}

func TalosClusterKubeconfigOutput(ctx *pulumi.Context, args TalosClusterKubeconfigOutputArgs, opts ...pulumi.InvokeOption) TalosClusterKubeconfigResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (TalosClusterKubeconfigResult, error) {
			args := v.(TalosClusterKubeconfigArgs)
			r, err := TalosClusterKubeconfig(ctx, &args, opts...)
			var s TalosClusterKubeconfigResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(TalosClusterKubeconfigResultOutput)
}

// A collection of arguments for invoking TalosClusterKubeconfig.
type TalosClusterKubeconfigOutputArgs struct {
	// The client configuration data
	ClientConfiguration TalosClusterKubeconfigClientConfigurationInput `pulumi:"clientConfiguration"`
	// endpoint to use for the talosclient. if not set, the node value will be used
	Endpoint pulumi.StringPtrInput `pulumi:"endpoint"`
	// controlplane node to retrieve the kubeconfig from
	Node     pulumi.StringInput `pulumi:"node"`
	Timeouts pulumi.MapInput    `pulumi:"timeouts"`
	// Wait for the kubernetes api to be available
	Wait pulumi.BoolPtrInput `pulumi:"wait"`
}

func (TalosClusterKubeconfigOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TalosClusterKubeconfigArgs)(nil)).Elem()
}

// A collection of values returned by TalosClusterKubeconfig.
type TalosClusterKubeconfigResultOutput struct{ *pulumi.OutputState }

func (TalosClusterKubeconfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TalosClusterKubeconfigResult)(nil)).Elem()
}

func (o TalosClusterKubeconfigResultOutput) ToTalosClusterKubeconfigResultOutput() TalosClusterKubeconfigResultOutput {
	return o
}

func (o TalosClusterKubeconfigResultOutput) ToTalosClusterKubeconfigResultOutputWithContext(ctx context.Context) TalosClusterKubeconfigResultOutput {
	return o
}

// The client configuration data
func (o TalosClusterKubeconfigResultOutput) ClientConfiguration() TalosClusterKubeconfigClientConfigurationOutput {
	return o.ApplyT(func(v TalosClusterKubeconfigResult) TalosClusterKubeconfigClientConfiguration {
		return v.ClientConfiguration
	}).(TalosClusterKubeconfigClientConfigurationOutput)
}

// endpoint to use for the talosclient. if not set, the node value will be used
func (o TalosClusterKubeconfigResultOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v TalosClusterKubeconfigResult) string { return v.Endpoint }).(pulumi.StringOutput)
}

// The ID of this resource.
func (o TalosClusterKubeconfigResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v TalosClusterKubeconfigResult) string { return v.Id }).(pulumi.StringOutput)
}

// The raw kubeconfig
func (o TalosClusterKubeconfigResultOutput) KubeconfigRaw() pulumi.StringOutput {
	return o.ApplyT(func(v TalosClusterKubeconfigResult) string { return v.KubeconfigRaw }).(pulumi.StringOutput)
}

// The kubernetes client configuration
func (o TalosClusterKubeconfigResultOutput) KubernetesClientConfiguration() TalosClusterKubeconfigKubernetesClientConfigurationOutput {
	return o.ApplyT(func(v TalosClusterKubeconfigResult) TalosClusterKubeconfigKubernetesClientConfiguration {
		return v.KubernetesClientConfiguration
	}).(TalosClusterKubeconfigKubernetesClientConfigurationOutput)
}

// controlplane node to retrieve the kubeconfig from
func (o TalosClusterKubeconfigResultOutput) Node() pulumi.StringOutput {
	return o.ApplyT(func(v TalosClusterKubeconfigResult) string { return v.Node }).(pulumi.StringOutput)
}

func (o TalosClusterKubeconfigResultOutput) Timeouts() pulumi.MapOutput {
	return o.ApplyT(func(v TalosClusterKubeconfigResult) map[string]interface{} { return v.Timeouts }).(pulumi.MapOutput)
}

// Wait for the kubernetes api to be available
func (o TalosClusterKubeconfigResultOutput) Wait() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v TalosClusterKubeconfigResult) *bool { return v.Wait }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(TalosClusterKubeconfigResultOutput{})
}
