// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package talos

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Generate a machine configuration for a node type
//
// > **Note:** It is recommended to set the optional `talosVersion` attribute.
// Otherwise when using a new version of the provider with a new major version of the Talos SDK, new machineconfig features will be enabled by default which could cause unexpected behavior.
//
// ## Example Usage
//
// {{tffile "examples/data-sources/talos_machine_configuration/data-source.tf"}}
func TalosMachineConfiguration(ctx *pulumi.Context, args *TalosMachineConfigurationArgs, opts ...pulumi.InvokeOption) (*TalosMachineConfigurationResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv TalosMachineConfigurationResult
	err := ctx.Invoke("talos:index/talosMachineConfiguration:TalosMachineConfiguration", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking TalosMachineConfiguration.
type TalosMachineConfigurationArgs struct {
	// The endpoint of the talos kubernetes cluster
	ClusterEndpoint string `pulumi:"clusterEndpoint"`
	// The name of the talos kubernetes cluster
	ClusterName string `pulumi:"clusterName"`
	// The list of config patches to apply to the generated configuration
	ConfigPatches []string `pulumi:"configPatches"`
	// Whether to generate documentation for the generated configuration
	Docs *bool `pulumi:"docs"`
	// Whether to generate examples for the generated configuration
	Examples *bool `pulumi:"examples"`
	// The version of kubernetes to use
	KubernetesVersion *string `pulumi:"kubernetesVersion"`
	// The secrets for the talos cluster
	MachineSecrets TalosMachineConfigurationMachineSecrets `pulumi:"machineSecrets"`
	// The type of machine to generate the configuration for
	MachineType string `pulumi:"machineType"`
	// The version of talos features to use in generated machine configuration
	TalosVersion *string `pulumi:"talosVersion"`
}

// A collection of values returned by TalosMachineConfiguration.
type TalosMachineConfigurationResult struct {
	// The endpoint of the talos kubernetes cluster
	ClusterEndpoint string `pulumi:"clusterEndpoint"`
	// The name of the talos kubernetes cluster
	ClusterName string `pulumi:"clusterName"`
	// The list of config patches to apply to the generated configuration
	ConfigPatches []string `pulumi:"configPatches"`
	// Whether to generate documentation for the generated configuration
	Docs *bool `pulumi:"docs"`
	// Whether to generate examples for the generated configuration
	Examples *bool `pulumi:"examples"`
	// The ID of this resource.
	Id string `pulumi:"id"`
	// The version of kubernetes to use
	KubernetesVersion *string `pulumi:"kubernetesVersion"`
	// The generated machine configuration
	MachineConfiguration string `pulumi:"machineConfiguration"`
	// The secrets for the talos cluster
	MachineSecrets TalosMachineConfigurationMachineSecrets `pulumi:"machineSecrets"`
	// The type of machine to generate the configuration for
	MachineType string `pulumi:"machineType"`
	// The version of talos features to use in generated machine configuration
	TalosVersion *string `pulumi:"talosVersion"`
}

func TalosMachineConfigurationOutput(ctx *pulumi.Context, args TalosMachineConfigurationOutputArgs, opts ...pulumi.InvokeOption) TalosMachineConfigurationResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (TalosMachineConfigurationResult, error) {
			args := v.(TalosMachineConfigurationArgs)
			r, err := TalosMachineConfiguration(ctx, &args, opts...)
			var s TalosMachineConfigurationResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(TalosMachineConfigurationResultOutput)
}

// A collection of arguments for invoking TalosMachineConfiguration.
type TalosMachineConfigurationOutputArgs struct {
	// The endpoint of the talos kubernetes cluster
	ClusterEndpoint pulumi.StringInput `pulumi:"clusterEndpoint"`
	// The name of the talos kubernetes cluster
	ClusterName pulumi.StringInput `pulumi:"clusterName"`
	// The list of config patches to apply to the generated configuration
	ConfigPatches pulumi.StringArrayInput `pulumi:"configPatches"`
	// Whether to generate documentation for the generated configuration
	Docs pulumi.BoolPtrInput `pulumi:"docs"`
	// Whether to generate examples for the generated configuration
	Examples pulumi.BoolPtrInput `pulumi:"examples"`
	// The version of kubernetes to use
	KubernetesVersion pulumi.StringPtrInput `pulumi:"kubernetesVersion"`
	// The secrets for the talos cluster
	MachineSecrets TalosMachineConfigurationMachineSecretsInput `pulumi:"machineSecrets"`
	// The type of machine to generate the configuration for
	MachineType pulumi.StringInput `pulumi:"machineType"`
	// The version of talos features to use in generated machine configuration
	TalosVersion pulumi.StringPtrInput `pulumi:"talosVersion"`
}

func (TalosMachineConfigurationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TalosMachineConfigurationArgs)(nil)).Elem()
}

// A collection of values returned by TalosMachineConfiguration.
type TalosMachineConfigurationResultOutput struct{ *pulumi.OutputState }

func (TalosMachineConfigurationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TalosMachineConfigurationResult)(nil)).Elem()
}

func (o TalosMachineConfigurationResultOutput) ToTalosMachineConfigurationResultOutput() TalosMachineConfigurationResultOutput {
	return o
}

func (o TalosMachineConfigurationResultOutput) ToTalosMachineConfigurationResultOutputWithContext(ctx context.Context) TalosMachineConfigurationResultOutput {
	return o
}

// The endpoint of the talos kubernetes cluster
func (o TalosMachineConfigurationResultOutput) ClusterEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) string { return v.ClusterEndpoint }).(pulumi.StringOutput)
}

// The name of the talos kubernetes cluster
func (o TalosMachineConfigurationResultOutput) ClusterName() pulumi.StringOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) string { return v.ClusterName }).(pulumi.StringOutput)
}

// The list of config patches to apply to the generated configuration
func (o TalosMachineConfigurationResultOutput) ConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) []string { return v.ConfigPatches }).(pulumi.StringArrayOutput)
}

// Whether to generate documentation for the generated configuration
func (o TalosMachineConfigurationResultOutput) Docs() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) *bool { return v.Docs }).(pulumi.BoolPtrOutput)
}

// Whether to generate examples for the generated configuration
func (o TalosMachineConfigurationResultOutput) Examples() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) *bool { return v.Examples }).(pulumi.BoolPtrOutput)
}

// The ID of this resource.
func (o TalosMachineConfigurationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) string { return v.Id }).(pulumi.StringOutput)
}

// The version of kubernetes to use
func (o TalosMachineConfigurationResultOutput) KubernetesVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) *string { return v.KubernetesVersion }).(pulumi.StringPtrOutput)
}

// The generated machine configuration
func (o TalosMachineConfigurationResultOutput) MachineConfiguration() pulumi.StringOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) string { return v.MachineConfiguration }).(pulumi.StringOutput)
}

// The secrets for the talos cluster
func (o TalosMachineConfigurationResultOutput) MachineSecrets() TalosMachineConfigurationMachineSecretsOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) TalosMachineConfigurationMachineSecrets {
		return v.MachineSecrets
	}).(TalosMachineConfigurationMachineSecretsOutput)
}

// The type of machine to generate the configuration for
func (o TalosMachineConfigurationResultOutput) MachineType() pulumi.StringOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) string { return v.MachineType }).(pulumi.StringOutput)
}

// The version of talos features to use in generated machine configuration
func (o TalosMachineConfigurationResultOutput) TalosVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TalosMachineConfigurationResult) *string { return v.TalosVersion }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(TalosMachineConfigurationResultOutput{})
}
