// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Applies machine configuration to a Talos node.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as talos from "@siderolabs/pulumi-talos";
 *
 * const machineSecrets = new talos.machine.Secrets("machineSecrets", {});
 * const talosconfig = new talos.client.Configuration("talosconfig", {
 *     clusterName: "example-cluster",
 *     machineSecrets: machineSecrets.machineSecrets,
 *     endpoints: ["10.5.0.2"],
 * });
 * const bootstrap = new talos.machine.Bootstrap("bootstrap", {
 *     talosConfig: talosconfig.talosConfig,
 *     endpoint: "10.5.0.2",
 *     node: "10.5.0.2",
 * });
 * ```
 */
export class Bootstrap extends pulumi.CustomResource {
    /**
     * Get an existing Bootstrap resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BootstrapState, opts?: pulumi.CustomResourceOptions): Bootstrap {
        return new Bootstrap(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'talos:machine/bootstrap:Bootstrap';

    /**
     * Returns true if the given object is an instance of Bootstrap.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Bootstrap {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Bootstrap.__pulumiType;
    }

    /**
     * machine endpoint
     */
    public readonly endpoint!: pulumi.Output<string>;
    /**
     * node to bootstrap
     */
    public readonly node!: pulumi.Output<string>;
    /**
     * talos client configuration for authentication
     */
    public readonly talosConfig!: pulumi.Output<string>;

    /**
     * Create a Bootstrap resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BootstrapArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BootstrapArgs | BootstrapState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BootstrapState | undefined;
            resourceInputs["endpoint"] = state ? state.endpoint : undefined;
            resourceInputs["node"] = state ? state.node : undefined;
            resourceInputs["talosConfig"] = state ? state.talosConfig : undefined;
        } else {
            const args = argsOrState as BootstrapArgs | undefined;
            if ((!args || args.endpoint === undefined) && !opts.urn) {
                throw new Error("Missing required property 'endpoint'");
            }
            if ((!args || args.node === undefined) && !opts.urn) {
                throw new Error("Missing required property 'node'");
            }
            if ((!args || args.talosConfig === undefined) && !opts.urn) {
                throw new Error("Missing required property 'talosConfig'");
            }
            resourceInputs["endpoint"] = args ? args.endpoint : undefined;
            resourceInputs["node"] = args ? args.node : undefined;
            resourceInputs["talosConfig"] = args ? args.talosConfig : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Bootstrap.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Bootstrap resources.
 */
export interface BootstrapState {
    /**
     * machine endpoint
     */
    endpoint?: pulumi.Input<string>;
    /**
     * node to bootstrap
     */
    node?: pulumi.Input<string>;
    /**
     * talos client configuration for authentication
     */
    talosConfig?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Bootstrap resource.
 */
export interface BootstrapArgs {
    /**
     * machine endpoint
     */
    endpoint: pulumi.Input<string>;
    /**
     * node to bootstrap
     */
    node: pulumi.Input<string>;
    /**
     * talos client configuration for authentication
     */
    talosConfig: pulumi.Input<string>;
}
