// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";

/**
 * Talos Certs type
 */
export interface CertsArgs {
    Admin?: pulumi.Input<inputs.PEMEncodedCertificateAndKeyArgs>;
    Etcd?: pulumi.Input<inputs.PEMEncodedCertificateAndKeyArgs>;
    K8s?: pulumi.Input<inputs.PEMEncodedCertificateAndKeyArgs>;
    K8sAggregator?: pulumi.Input<inputs.PEMEncodedCertificateAndKeyArgs>;
    K8sServiceAccount?: pulumi.Input<inputs.PEMEncodedKeyArgs>;
    OS?: pulumi.Input<inputs.PEMEncodedCertificateAndKeyArgs>;
}

/**
 * Talos Cluster type
 */
export interface ClusterArgs {
    Id?: pulumi.Input<string>;
    Secret?: pulumi.Input<string>;
}

/**
 * patches applied to the config
 */
export interface ConfigPatchesArgs {
    /**
     * patches specified as pulumi file assets
     */
    patchFiles?: pulumi.Input<pulumi.Input<pulumi.asset.Asset | pulumi.asset.Archive>[]>;
    /**
     * patches specified as a pulumi map
     */
    patches?: pulumi.Input<any[]>;
}

/**
 * Talos PEMEncodedCertificateAndKey type
 */
export interface PEMEncodedCertificateAndKeyArgs {
    Crt?: any;
    Key?: any;
}

/**
 * Talos PEMEncodedKey type
 */
export interface PEMEncodedKeyArgs {
    Key?: any;
}

/**
 * Talos Secrets type
 */
export interface SecretsArgs {
    AESCBCEncryptionSecret?: pulumi.Input<string>;
    BootstrapToken?: pulumi.Input<string>;
}

/**
 * Talos SecretsBundle type
 */
export interface SecretsBundleArgs {
    Certs?: pulumi.Input<inputs.CertsArgs>;
    Cluster?: pulumi.Input<inputs.ClusterArgs>;
    Secrets?: pulumi.Input<inputs.SecretsArgs>;
    TrustdInfo?: pulumi.Input<inputs.TrustdInfoArgs>;
}

/**
 * Talos Machine Configuration Version
 */
export interface TalosMachineConfigVersionOutputArgs {
}

/**
 * Talos Version
 */
export interface TalosVersionOutputArgs {
}

/**
 * Talos TrustdInfo type
 */
export interface TrustdInfoArgs {
    Token?: pulumi.Input<string>;
}
