// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Talos.ImageFactory.Inputs
{

    public sealed class GetOverlaysVersionsFiltersInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the overlay to filter by.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetOverlaysVersionsFiltersInputArgs()
        {
        }
        public static new GetOverlaysVersionsFiltersInputArgs Empty => new GetOverlaysVersionsFiltersInputArgs();
    }
}
