// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Talos.Inputs
{

    /// <summary>
    /// Talos Certs type
    /// </summary>
    public sealed class CertsArgs : Pulumi.ResourceArgs
    {
        [Input("Admin")]
        public Input<Inputs.PEMEncodedCertificateAndKeyArgs>? Admin { get; set; }

        [Input("Etcd")]
        public Input<Inputs.PEMEncodedCertificateAndKeyArgs>? Etcd { get; set; }

        [Input("K8s")]
        public Input<Inputs.PEMEncodedCertificateAndKeyArgs>? K8s { get; set; }

        [Input("K8sAggregator")]
        public Input<Inputs.PEMEncodedCertificateAndKeyArgs>? K8sAggregator { get; set; }

        [Input("K8sServiceAccount")]
        public Input<Inputs.PEMEncodedKeyArgs>? K8sServiceAccount { get; set; }

        [Input("OS")]
        public Input<Inputs.PEMEncodedCertificateAndKeyArgs>? OS { get; set; }

        public CertsArgs()
        {
        }
    }
}
