// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The image factory extensions versions data source provides a list of available extensions for a specific talos version from the image factory.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as talos from "@pulumi/talos";
 *
 * const this = talos.getImageFactoryExtensionsVersions({
 *     talosVersion: "v1.7.5",
 *     filters: {
 *         names: [
 *             "amdgpu",
 *             "tailscale",
 *         ],
 *     },
 * });
 * ```
 */
export function getImageFactoryExtensionsVersions(args: GetImageFactoryExtensionsVersionsArgs, opts?: pulumi.InvokeOptions): Promise<GetImageFactoryExtensionsVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("talos:index/getImageFactoryExtensionsVersions:getImageFactoryExtensionsVersions", {
        "filters": args.filters,
        "talosVersion": args.talosVersion,
    }, opts);
}

/**
 * A collection of arguments for invoking getImageFactoryExtensionsVersions.
 */
export interface GetImageFactoryExtensionsVersionsArgs {
    /**
     * The filter to apply to the extensions list.
     */
    filters?: inputs.GetImageFactoryExtensionsVersionsFilters;
    /**
     * The talos version to get extensions for.
     */
    talosVersion: string;
}

/**
 * A collection of values returned by getImageFactoryExtensionsVersions.
 */
export interface GetImageFactoryExtensionsVersionsResult {
    /**
     * The list of available extensions for the specified talos version.
     */
    readonly extensionsInfos: outputs.GetImageFactoryExtensionsVersionsExtensionsInfo[];
    /**
     * The filter to apply to the extensions list.
     */
    readonly filters?: outputs.GetImageFactoryExtensionsVersionsFilters;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * The talos version to get extensions for.
     */
    readonly talosVersion: string;
}
/**
 * The image factory extensions versions data source provides a list of available extensions for a specific talos version from the image factory.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as talos from "@pulumi/talos";
 *
 * const this = talos.getImageFactoryExtensionsVersions({
 *     talosVersion: "v1.7.5",
 *     filters: {
 *         names: [
 *             "amdgpu",
 *             "tailscale",
 *         ],
 *     },
 * });
 * ```
 */
export function getImageFactoryExtensionsVersionsOutput(args: GetImageFactoryExtensionsVersionsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetImageFactoryExtensionsVersionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("talos:index/getImageFactoryExtensionsVersions:getImageFactoryExtensionsVersions", {
        "filters": args.filters,
        "talosVersion": args.talosVersion,
    }, opts);
}

/**
 * A collection of arguments for invoking getImageFactoryExtensionsVersions.
 */
export interface GetImageFactoryExtensionsVersionsOutputArgs {
    /**
     * The filter to apply to the extensions list.
     */
    filters?: pulumi.Input<inputs.GetImageFactoryExtensionsVersionsFiltersArgs>;
    /**
     * The talos version to get extensions for.
     */
    talosVersion: pulumi.Input<string>;
}
